{% set name = "django-linear-migrations" %}
{% set version = "2.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django_linear_migrations-{{ version }}.tar.gz
  sha256: cb6f8dd05de796326af7064eb1822505b16cbbbcb9b2ccef940576e4942d5eda

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - django_linear_migrations
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-linear-migrations
  summary: Ensure your migrations are linear.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
